# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20170218_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompany',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
