# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20170218_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcompany',
            name='dateAdded',
            field=models.DateTimeField(),
        ),
    ]
