# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblCAPEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('preStrip', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mineEquipInitial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mineEquipSustain', models.DecimalField(decimal_places=2, max_digits=20)),
                ('infraDirectCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('infraIndirectCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contingency', models.DecimalField(decimal_places=2, max_digits=20)),
                ('railcars', models.DecimalField(decimal_places=2, max_digits=20)),
                ('otherMobEquip', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closureRehabAssure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depoProvisionPay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('workCapCurrentProd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('workCapCostsLG', models.DecimalField(decimal_places=2, max_digits=20)),
                ('EPCM', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ownerCost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dateAdded', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblCAPEX',
            },
        ),
        migrations.CreateModel(
            name='tblCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblCommodity',
            },
        ),
        migrations.CreateModel(
            name='tblCommodityList',
            fields=[
                ('commodityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('commodityType', models.IntegerField()),
            ],
            options={
                'db_table': 'tblCommodityList',
            },
        ),
        migrations.CreateModel(
            name='tblMine',
            fields=[
                ('mineID', models.AutoField(primary_key=True, serialize=False)),
                ('mine', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalCode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=32)),
                ('dateAdded', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblMine',
            },
        ),
        migrations.CreateModel(
            name='tblMineProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('mineID', models.ForeignKey(db_column='mineID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMine')),
            ],
            options={
                'db_table': 'tblMineProduct',
            },
        ),
        migrations.CreateModel(
            name='tblMineProductList',
            fields=[
                ('mineProductID', models.AutoField(primary_key=True, serialize=False)),
                ('mineProduct', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tblMineProductList',
            },
        ),
        migrations.CreateModel(
            name='tblOPEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mining', models.DecimalField(decimal_places=2, max_digits=20)),
                ('infrastructure', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stockpileLG', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dewatering', models.DecimalField(decimal_places=2, max_digits=20)),
                ('processing', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hauling', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loadOutRailLoop', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GASite', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GARoomBoardFIFO', models.DecimalField(decimal_places=2, max_digits=20)),
                ('railTransport', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GACorp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('royalties', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transportation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('GA', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dateAdded', models.DateTimeField()),
                ('mineID', models.ForeignKey(db_column='mineID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMine')),
            ],
            options={
                'db_table': 'tblOPEX',
            },
        ),
        migrations.CreateModel(
            name='tblPlantProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('mineID', models.ForeignKey(db_column='mineID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMine')),
            ],
            options={
                'db_table': 'tblPlantProduct',
            },
        ),
        migrations.CreateModel(
            name='tblPlantProductList',
            fields=[
                ('plantProductID', models.AutoField(primary_key=True, serialize=False)),
                ('plantProduct', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tblPlantProductList',
            },
        ),
        migrations.CreateModel(
            name='tblProject',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('LOM', models.IntegerField()),
                ('dateAdded', models.DateTimeField()),
                ('mineID', models.ForeignKey(db_column='mineID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMine')),
            ],
            options={
                'db_table': 'tblProject',
            },
        ),
        migrations.CreateModel(
            name='tblProjectTypeList',
            fields=[
                ('projectTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('projectType', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tblProjectTypeList',
            },
        ),
        migrations.AddField(
            model_name='tblproject',
            name='projectTypeID',
            field=models.ForeignKey(db_column='projectTypeID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblProjectTypeList'),
        ),
        migrations.AddField(
            model_name='tblplantproduct',
            name='plantProductID',
            field=models.ForeignKey(db_column='plantProductID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblPlantProductList'),
        ),
        migrations.AddField(
            model_name='tblmineproduct',
            name='mineProductID',
            field=models.ForeignKey(db_column='mineProductID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMineProductList'),
        ),
        migrations.AddField(
            model_name='tblcommodity',
            name='commodityID',
            field=models.ForeignKey(db_column='commodityID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblCommodityList'),
        ),
        migrations.AddField(
            model_name='tblcommodity',
            name='mineID',
            field=models.ForeignKey(db_column='mineID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMine'),
        ),
        migrations.AddField(
            model_name='tblcapex',
            name='mineID',
            field=models.ForeignKey(db_column='mineID', on_delete=django.db.models.deletion.CASCADE, to='setup.tblMine'),
        ),
    ]
